### PR TITLE
Node.js support, baseURI fix

### PR DESCRIPTION
**Pull request by bergos**
- replace `Node.*`constants for xmldom / Node.js support
- added ComonJS/npm support
- added baseURI option for documents different than the current and Node.js support

### CODE REVIEW

**Comment by elf-pavlik** [comment]
I guess it solves #3 
@davidlehn after this merge you could most likely add green-turtle as dependency to jsonld-request instead keeping modified copy https://github.com/digitalbazaar/jsonld-request/blob/master/lib/rdfa.js

**Comment by elf-pavlik** [comment]
@sballesteros do you think green-turtle can pull in something from https://github.com/scienceai/graph-rdfa-processor ?

**Comment by sballesteros** [comment]
@elf-pavlik absolutely!  Ideally green-turtle could directly `require` / `import` graph-rdfa-processor. graph-rdfa-processor could also export most of the sub classes it needs that are also used by green-turtle.

Some more context:
I pinged @alexmilowski when I did that but I guess he was too busy at the time. The reason I started that was precisely to be able to replace https://github.com/digitalbazaar/jsonld-request/blob/master/lib/rdfa.js in the jsonld.js library like you mention in https://github.com/alexmilowski/green-turtle/pull/8#issuecomment-210687569 (https://www.npmjs.com/package/node-green-turtle does not include enough of the green-turtle code base to achieve that, and also I wanted to have a library easy to consume from node.js / browserify (so not ant / Java build step etc.) and following more idiomatic error reporting (using Error instead of plain strings). 
I mostly use graph-rdfa-processor  for that purpose see for instance https://github.com/scienceai/jsonld-rdfa-parser.  I need to send some PR to the json-ld.js lib but have been super busy working on https://science.ai. If there is interest I would love to help making that happen!

**Comment by elf-pavlik** [comment]
@alexmilowski replied to my email few days ago that now he will have time for improving green-turtle and take a look at this PR :tada: 

I would like to invite both of you to consider coordinating efforts with participants of RDFJS CG 
* https://github.com/rdfjs/rdfjs.github.io

Which already provides online ground where people working on [rdf-ext](https://github.com/rdf-ext/rdf-ext), [rdflib.js](https://github.com/linkeddata/rdflib.js), [jsonld.js](https://github.com/digitalbazaar/jsonld.js) etc. start coordinating efforts! :boom:

**Comment by alexmilowski** [comment]
Hello all,

Looks good.  Sorry it took me so long to get to this.

**Pull request merged**
